export default {
    DATABASE_PORT: 'DB_PORT',
    DATABASE_HOST: 'DB_HOST',
    DATABASE_PASS: 'DB_PASS',
    DATABASE_NAME: 'DB_NAME',
    DATABASE_USER: 'DB_USER',
    NODE_ENV: 'NODE_ENV',
    PRODUCTION: 'PRODUCTION',
    DATABASE_TYPE: 'DB_TYPE',
};
